### PR TITLE
Allow to map files with duplicated column names

### PR DESCRIPTION
**Pull request by diogomafra**
When a file has more than one column with the same name, the first one
will keep the original name and the others are going to be identified by
a random name.

To map these columns the user should map by index.

### CODE REVIEW

**Comment by diogomafra** [comment]
Could you update the Nuget version after merging this PR? Thank you!

**Comment by hughbe** [comment]
This is great, thanks. Looks like the issue was that it would throw an ArgumentException when reading the columns.
I think it'd be overkill to provide some kind of API that can, for example, get the 2nd occurence of a column names. The column index is enough.

BTW how are you using the library? Let me know if you've encountered any other tough spots or bugs and if you have an questions!

**Comment by hughbe** [comment]
I've released ExcelDataReader.Mapping 0.9.0: https://www.nuget.org/packages/ExcelDataReader.Mapping/0.9.0

Might take 5-10mins to pop up in the nuget index

**Comment by diogomafra** [comment]
Yes, I've started to use your library and these two PR cover all problems I've encountered.

I agree with you, the solution I gave in this PR is very simple, I don't think it's worth expending much time dealing with repeated column names. It's an edge case that can be solved by mapping by index.

Thank you very much for creating this library. It's very easy to use, well documented and works great!

**Pull request merged**
