### PR TITLE
Storing the row index inside the ReadCellValueResult struct

### PR DESCRIPTION
**Pull request by joao29a**
I think it would be good to have this value stored, so it's possible to work with the column index and row index inside the WithConverter extension method, giving the possibility to point it out the position of where the convertion failed inside the excel.

### CODE REVIEW

**Comment by hughbe** [comment]
Hey buddy thanks for this!

I like this quite a lot as an idea actually.

I also think actually we should move the Sheet property into ReadCellValueResult as well. 

Since I’m making breaking changes and bumping up the major version in #62, we could think about renaming ReadCellValueResult to ReadCellValueContext as that more accurately represents the meaning of the struct. We could also remove the `ExcelSheet sheet` and `int columnIndex` parameters from ICellValueReader. What do you think?

Also take a look at that PR. It’s aim to make it a lot easier to detect errors, handle them and know where they occurred.

it’s good to see that there’s demand for better exception handling. This will be something ima work on during lockdown 3 in U.K. :))

**Comment by hughbe** [comment]
Also please let me know any problems/bugs/weird things you’ve encountered with the library and any feature requests - can work it out

**Comment by joao29a** [comment]
Looking at https://github.com/hughbe/excel-mapper/pull/62 it's just the thing I need. I can implement my own FallbackItem and getting the exception thrown, so it's possible to show the user the exact error and point it out the row and column index.

I don't thing these changes is necessary anymore.

**Comment by hughbe** [comment]
I've published https://www.nuget.org/packages/ExcelDataReader.Mapping/2.2.0

Do close this PR if you think it is no longer necessary!

**Comment by hughbe** [comment]
I'll close this now

**Pull request closed without merging**
